CREATE TABLE BOOK(
  BOOK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BARCODE VARCHAR(50),
  TITLE VARCHAR(100) NOT NULL,
  AUTHOR VARCHAR(100) NOT NULL
);

CREATE TABLE GUEST(
  GUEST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BARCODE VARCHAR(50),
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
);

CREATE TABLE CHECKOUT(
  CHECKOUT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BOOK_ID BIGINT NOT NULL,
  GUEST_ID BIGINT NOT NULL,
  CHECKOUT_DATE DATE,
  DUE_DATE DATE,
  RETURN_DATE DATE
);

ALTER TABLE CHECKOUT ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID);
ALTER TABLE CHECKOUT ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID);
